//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YelloKiller.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Scores : global::System.Configuration.ApplicationSettingsBase {
        
        private static Scores defaultInstance = ((Scores)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Scores())));
        
        public static Scores Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kassociés")]
        public string Name_01 {
            get {
                return ((string)(this["Name_01"]));
            }
            set {
                this["Name_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90000")]
        public uint Score_01 {
            get {
                return ((uint)(this["Score_01"]));
            }
            set {
                this["Score_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kassociés")]
        public string Name_02 {
            get {
                return ((string)(this["Name_02"]));
            }
            set {
                this["Name_02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80000")]
        public uint Score_02 {
            get {
                return ((uint)(this["Score_02"]));
            }
            set {
                this["Score_02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kassociés")]
        public string Name_03 {
            get {
                return ((string)(this["Name_03"]));
            }
            set {
                this["Name_03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70000")]
        public uint Score_03 {
            get {
                return ((uint)(this["Score_03"]));
            }
            set {
                this["Score_03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kassociés")]
        public string Name_04 {
            get {
                return ((string)(this["Name_04"]));
            }
            set {
                this["Name_04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public uint Score_04 {
            get {
                return ((uint)(this["Score_04"]));
            }
            set {
                this["Score_04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kassociés")]
        public string Name_05 {
            get {
                return ((string)(this["Name_05"]));
            }
            set {
                this["Name_05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public uint Score_05 {
            get {
                return ((uint)(this["Score_05"]));
            }
            set {
                this["Score_05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kassociés")]
        public string Name_06 {
            get {
                return ((string)(this["Name_06"]));
            }
            set {
                this["Name_06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40000")]
        public uint Score_06 {
            get {
                return ((uint)(this["Score_06"]));
            }
            set {
                this["Score_06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kassociés")]
        public string Name_07 {
            get {
                return ((string)(this["Name_07"]));
            }
            set {
                this["Name_07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public uint Score_07 {
            get {
                return ((uint)(this["Score_07"]));
            }
            set {
                this["Score_07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kassociés")]
        public string Name_08 {
            get {
                return ((string)(this["Name_08"]));
            }
            set {
                this["Name_08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public uint Score_08 {
            get {
                return ((uint)(this["Score_08"]));
            }
            set {
                this["Score_08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kassociés")]
        public string Name_09 {
            get {
                return ((string)(this["Name_09"]));
            }
            set {
                this["Name_09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public uint Score_09 {
            get {
                return ((uint)(this["Score_09"]));
            }
            set {
                this["Score_09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kassociés")]
        public string Name_10 {
            get {
                return ((string)(this["Name_10"]));
            }
            set {
                this["Name_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public uint Score_10 {
            get {
                return ((uint)(this["Score_10"]));
            }
            set {
                this["Score_10"] = value;
            }
        }
    }
}
